// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/jflex.flex

/* JFlex example: partial Java language lexer specification */
import java_cup.runtime.*;

/**
  * This class is a simple example lexer.
  */

@SuppressWarnings("fallthrough")
class LexerProyUno implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int MULTILINECOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\2\u0100\1\u0200\1\u0300\33\u0100\1\u0400\267\u0100\10\u0500"+
    "\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\1"+
    "\1\5\1\6\2\0\1\7\1\0\1\10\2\0\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\11\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\32\30\1\31"+
    "\1\32\1\33\1\34\1\30\1\0\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\30\1\46"+
    "\1\47\1\30\1\50\1\51\1\52\1\30\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\2\30\1\0\1\62"+
    "\1\0\1\63\6\0\1\3\33\0\1\64\35\0\1\65"+
    "\u01e3\0\1\66\251\0\1\67\6\0\1\70\323\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\17\24\1\2\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\1\1\2\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\2\0\1\50\1\51\1\52"+
    "\20\24\1\53\3\24\1\54\4\24\1\55\1\56\1\57"+
    "\1\60\1\61\1\37\1\0\1\62\6\24\1\63\3\24"+
    "\1\64\1\65\1\24\1\66\12\24\1\0\1\67\1\24"+
    "\1\70\1\71\1\24\1\72\1\73\1\74\1\24\1\75"+
    "\1\24\1\76\2\24\1\77\1\24\1\100\1\101\1\102"+
    "\1\24\1\103\1\24\1\104\1\105\3\24\1\106\1\107"+
    "\1\24\1\110\1\111\1\112";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\344\0\u011d\0\344"+
    "\0\344\0\344\0\344\0\u0156\0\344\0\u018f\0\u01c8\0\u0201"+
    "\0\u023a\0\344\0\344\0\u0273\0\u02ac\0\u02e5\0\344\0\344"+
    "\0\u031e\0\344\0\344\0\344\0\u0357\0\u0390\0\u03c9\0\u0402"+
    "\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca"+
    "\0\u0603\0\u063c\0\u0675\0\u06ae\0\344\0\344\0\344\0\344"+
    "\0\344\0\u06e7\0\344\0\u0720\0\344\0\344\0\u0759\0\u0792"+
    "\0\344\0\344\0\344\0\344\0\344\0\344\0\u07cb\0\u0201"+
    "\0\344\0\344\0\344\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8"+
    "\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0"+
    "\0\u0ae9\0\u0b22\0\u0b5b\0\u031e\0\u0b94\0\u0bcd\0\u0c06\0\u031e"+
    "\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\344\0\344\0\344\0\344"+
    "\0\344\0\344\0\u0d23\0\u07cb\0\u0d5c\0\u0d95\0\u0dce\0\u0e07"+
    "\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u031e\0\u031e"+
    "\0\u0f96\0\u031e\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec"+
    "\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u031e\0\u1242\0\u031e"+
    "\0\u031e\0\u127b\0\u031e\0\u031e\0\u031e\0\u12b4\0\u031e\0\u12ed"+
    "\0\u031e\0\u1326\0\u135f\0\u031e\0\u1398\0\u031e\0\u031e\0\u031e"+
    "\0\u13d1\0\u031e\0\u140a\0\u031e\0\u031e\0\u1443\0\u147c\0\u14b5"+
    "\0\u031e\0\u031e\0\u14ee\0\u031e\0\u031e\0\u031e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\5\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\5\1\33\1\34\1\31\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\31\1\43\1\31\1\44\1\45"+
    "\1\46\1\31\1\47\1\50\1\51\1\31\1\52\1\53"+
    "\1\31\1\54\1\55\1\56\1\57\1\60\1\5\1\61"+
    "\2\62\1\5\3\62\1\63\23\62\1\64\36\62\10\65"+
    "\1\66\21\65\1\67\36\65\41\6\1\70\25\6\1\71"+
    "\1\6\115\0\1\72\56\0\1\73\72\0\1\74\10\0"+
    "\1\75\61\0\1\76\67\0\1\77\1\0\2\100\65\0"+
    "\1\77\1\0\2\21\74\0\1\101\70\0\1\102\70\0"+
    "\1\103\63\0\2\31\7\0\1\31\4\0\25\31\26\0"+
    "\2\31\7\0\1\31\4\0\14\31\1\104\1\31\1\105"+
    "\6\31\26\0\2\31\7\0\1\31\4\0\7\31\1\106"+
    "\4\31\1\107\10\31\26\0\2\31\7\0\1\31\4\0"+
    "\4\31\1\110\20\31\26\0\2\31\7\0\1\31\4\0"+
    "\12\31\1\111\1\112\10\31\1\113\26\0\2\31\7\0"+
    "\1\31\4\0\1\114\11\31\1\115\1\31\1\116\10\31"+
    "\26\0\2\31\7\0\1\31\4\0\4\31\1\117\3\31"+
    "\1\120\14\31\26\0\2\31\7\0\1\31\4\0\13\31"+
    "\1\121\11\31\26\0\2\31\7\0\1\31\4\0\14\31"+
    "\1\122\10\31\26\0\2\31\7\0\1\31\4\0\1\123"+
    "\24\31\26\0\2\31\7\0\1\31\4\0\5\31\1\124"+
    "\17\31\26\0\2\31\7\0\1\31\4\0\4\31\1\125"+
    "\20\31\26\0\2\31\7\0\1\31\4\0\7\31\1\126"+
    "\10\31\1\127\4\31\26\0\2\31\7\0\1\31\4\0"+
    "\14\31\1\130\1\31\1\131\6\31\26\0\2\31\7\0"+
    "\1\31\4\0\14\31\1\132\10\31\26\0\2\31\7\0"+
    "\1\31\4\0\7\31\1\133\4\31\1\134\10\31\7\0"+
    "\2\54\3\0\64\54\2\62\1\0\3\62\1\0\23\62"+
    "\1\0\36\62\6\0\1\135\41\0\1\136\2\0\1\137"+
    "\1\0\1\140\23\0\1\141\21\0\1\142\15\0\1\136"+
    "\2\0\1\137\1\0\1\140\63\0\1\143\37\0\2\144"+
    "\67\0\2\31\7\0\1\31\4\0\14\31\1\145\10\31"+
    "\26\0\2\31\7\0\1\31\4\0\4\31\1\146\20\31"+
    "\26\0\2\31\7\0\1\31\4\0\1\147\24\31\26\0"+
    "\2\31\7\0\1\31\4\0\1\150\24\31\26\0\2\31"+
    "\7\0\1\31\4\0\2\31\1\151\22\31\26\0\2\31"+
    "\7\0\1\31\4\0\17\31\1\152\5\31\26\0\2\31"+
    "\7\0\1\31\4\0\3\31\1\153\21\31\26\0\2\31"+
    "\7\0\1\31\4\0\10\31\1\154\14\31\26\0\2\31"+
    "\7\0\1\31\4\0\12\31\1\155\12\31\26\0\2\31"+
    "\7\0\1\31\4\0\14\31\1\156\10\31\26\0\2\31"+
    "\7\0\1\31\4\0\16\31\1\157\6\31\26\0\2\31"+
    "\7\0\1\31\4\0\20\31\1\160\4\31\26\0\2\31"+
    "\7\0\1\31\4\0\5\31\1\161\17\31\26\0\2\31"+
    "\7\0\1\31\4\0\20\31\1\162\4\31\26\0\2\31"+
    "\7\0\1\31\4\0\2\31\1\163\11\31\1\164\10\31"+
    "\26\0\2\31\7\0\1\31\4\0\22\31\1\165\2\31"+
    "\26\0\2\31\7\0\1\31\4\0\20\31\1\166\4\31"+
    "\26\0\2\31\7\0\1\31\4\0\14\31\1\167\10\31"+
    "\26\0\2\31\7\0\1\31\4\0\16\31\1\170\6\31"+
    "\26\0\2\31\7\0\1\31\4\0\21\31\1\171\3\31"+
    "\26\0\2\31\7\0\1\31\4\0\10\31\1\172\14\31"+
    "\26\0\2\31\7\0\1\31\4\0\4\31\1\173\20\31"+
    "\26\0\2\31\7\0\1\31\4\0\16\31\1\174\6\31"+
    "\47\0\1\175\47\0\2\31\7\0\1\31\4\0\12\31"+
    "\1\176\12\31\26\0\2\31\7\0\1\31\4\0\1\177"+
    "\24\31\26\0\2\31\7\0\1\31\4\0\16\31\1\200"+
    "\6\31\26\0\2\31\7\0\1\31\4\0\12\31\1\201"+
    "\12\31\26\0\2\31\7\0\1\31\4\0\10\31\1\202"+
    "\14\31\26\0\2\31\7\0\1\31\4\0\4\31\1\203"+
    "\20\31\26\0\2\31\7\0\1\31\4\0\12\31\1\204"+
    "\12\31\26\0\2\31\7\0\1\31\4\0\20\31\1\205"+
    "\4\31\26\0\2\31\7\0\1\31\4\0\17\31\1\171"+
    "\5\31\26\0\2\31\7\0\1\31\4\0\1\206\24\31"+
    "\26\0\2\31\7\0\1\31\4\0\20\31\1\207\4\31"+
    "\26\0\2\31\7\0\1\31\4\0\1\210\24\31\26\0"+
    "\2\31\7\0\1\31\4\0\15\31\1\211\7\31\26\0"+
    "\2\31\7\0\1\31\4\0\10\31\1\212\14\31\26\0"+
    "\2\31\7\0\1\31\4\0\21\31\1\213\3\31\26\0"+
    "\2\31\7\0\1\31\4\0\23\31\1\214\1\31\26\0"+
    "\2\31\7\0\1\31\4\0\10\31\1\215\14\31\26\0"+
    "\2\31\7\0\1\31\4\0\4\31\1\216\20\31\26\0"+
    "\2\31\7\0\1\31\4\0\3\31\1\217\21\31\26\0"+
    "\2\31\7\0\1\31\4\0\13\31\1\220\11\31\26\0"+
    "\2\31\7\0\1\31\4\0\12\31\1\221\12\31\56\0"+
    "\1\6\40\0\2\31\7\0\1\31\4\0\11\31\1\222"+
    "\13\31\26\0\2\31\7\0\1\31\4\0\3\31\1\223"+
    "\21\31\26\0\2\31\7\0\1\31\4\0\20\31\1\224"+
    "\4\31\26\0\2\31\7\0\1\31\4\0\12\31\1\225"+
    "\12\31\26\0\2\31\7\0\1\31\4\0\3\31\1\226"+
    "\21\31\26\0\2\31\7\0\1\31\4\0\16\31\1\227"+
    "\6\31\26\0\2\31\7\0\1\31\4\0\13\31\1\230"+
    "\11\31\26\0\2\31\7\0\1\31\4\0\3\31\1\231"+
    "\21\31\26\0\2\31\7\0\1\31\4\0\4\31\1\232"+
    "\20\31\26\0\2\31\7\0\1\31\4\0\1\233\24\31"+
    "\26\0\2\31\7\0\1\31\4\0\13\31\1\234\11\31"+
    "\26\0\2\31\7\0\1\31\4\0\6\31\1\235\16\31"+
    "\26\0\2\31\7\0\1\31\4\0\3\31\1\236\21\31"+
    "\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5415];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\1\1\4\11\1\1\1\11\4\1\2\11"+
    "\3\1\2\11\1\1\3\11\20\1\5\11\1\1\1\11"+
    "\1\1\2\11\2\1\6\11\2\0\3\11\31\1\6\11"+
    "\1\0\31\1\1\0\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerProyUno(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              System.err.println("Error: no se cerro el string");
                               yybegin(YYINITIAL); 
                               return symbol(sym.STRING_LITERAL, string.toString());
            }  // fall though
            case 159: break;
            case CHAR: {
              System.err.println("Error: no se cerro el caracter");
                               yybegin(YYINITIAL); 
                               return symbol(sym.CHAR_LITERAL, '\0');
            }  // fall though
            case 160: break;
            case MULTILINECOMMENT: {
              System.err.println("Error, no fue cerrado el comentario"); 
                               yybegin(YYINITIAL);
            }  // fall though
            case 161: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("error en línea " + (yyline+1) + ", columna " + (yycolumn+1) + ": Carácter inválido '" + yytext() + "'");
            }
          // fall through
          case 75: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 76: break;
          case 3:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 77: break;
          case 4:
            { string.setLength(0); yybegin(STRING);
            }
          // fall through
          case 78: break;
          case 5:
            { return symbol(sym.MOD);
            }
          // fall through
          case 79: break;
          case 6:
            { string.setLength(0); yybegin(CHAR);
            }
          // fall through
          case 80: break;
          case 7:
            { return symbol(sym.TIMES);
            }
          // fall through
          case 81: break;
          case 8:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 82: break;
          case 9:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 83: break;
          case 10:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 84: break;
          case 11:
            { return symbol(sym.DIV_FLOAT);
            }
          // fall through
          case 85: break;
          case 12:
            { return symbol(sym.INTEGER_LITERAL, Integer.parseInt(yytext()));
            }
          // fall through
          case 86: break;
          case 13:
            { return symbol(sym.COLON);
            }
          // fall through
          case 87: break;
          case 14:
            { return symbol(sym.SEMI);
            }
          // fall through
          case 88: break;
          case 15:
            { return symbol(sym.LT);
            }
          // fall through
          case 89: break;
          case 16:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 90: break;
          case 17:
            { return symbol(sym.GT);
            }
          // fall through
          case 91: break;
          case 18:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 92: break;
          case 19:
            { return symbol(sym.AND);
            }
          // fall through
          case 93: break;
          case 20:
            { return symbol(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 94: break;
          case 21:
            { return symbol(sym.DECLBRACKETL, yytext());
            }
          // fall through
          case 95: break;
          case 22:
            { return symbol(sym.DECLBRACKETR, yytext());
            }
          // fall through
          case 96: break;
          case 23:
            { return symbol(sym.POW);
            }
          // fall through
          case 97: break;
          case 24:
            { return symbol(sym.OR);
            }
          // fall through
          case 98: break;
          case 25:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 99: break;
          case 26:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 100: break;
          case 27:
            { return symbol(sym.NOT);
            }
          // fall through
          case 101: break;
          case 28:
            { yybegin(MULTILINECOMMENT);
            }
          // fall through
          case 102: break;
          case 29:
            { string.append( yytext() );
            }
          // fall through
          case 103: break;
          case 30:
            { yybegin(YYINITIAL); 
                                    return symbol(sym.STRING_LITERAL, 
                                    string.toString());
            }
          // fall through
          case 104: break;
          case 31:
            { string.append('\\');
            }
          // fall through
          case 105: break;
          case 32:
            { string.append(yytext());
            }
          // fall through
          case 106: break;
          case 33:
            { yybegin(YYINITIAL); 
                               return symbol(sym.CHAR_LITERAL, string.length() > 0 ? string.charAt(0) : '\0');
            }
          // fall through
          case 107: break;
          case 34:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 108: break;
          case 35:
            { return symbol(sym.NE);
            }
          // fall through
          case 109: break;
          case 36:
            { return symbol(sym.INC);
            }
          // fall through
          case 110: break;
          case 37:
            { return symbol(sym.DEC);
            }
          // fall through
          case 111: break;
          case 38:
            { return symbol(sym.ARROW);
            }
          // fall through
          case 112: break;
          case 39:
            { return symbol(sym.DIV_INT);
            }
          // fall through
          case 113: break;
          case 40:
            { return symbol(sym.LE);
            }
          // fall through
          case 114: break;
          case 41:
            { return symbol(sym.EQ);
            }
          // fall through
          case 115: break;
          case 42:
            { return symbol(sym.GE);
            }
          // fall through
          case 116: break;
          case 43:
            { return symbol(sym.OF);
            }
          // fall through
          case 117: break;
          case 44:
            { return symbol(sym.TO);
            }
          // fall through
          case 118: break;
          case 45:
            { string.append('\"');
            }
          // fall through
          case 119: break;
          case 46:
            { string.append('\n');
            }
          // fall through
          case 120: break;
          case 47:
            { string.append('\r');
            }
          // fall through
          case 121: break;
          case 48:
            { string.append('\t');
            }
          // fall through
          case 122: break;
          case 49:
            { string.append('\'');
            }
          // fall through
          case 123: break;
          case 50:
            { return symbol(sym.FLOAT_LITERAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 124: break;
          case 51:
            { return symbol(sym.END);
            }
          // fall through
          case 125: break;
          case 52:
            { return symbol(sym.FOR);
            }
          // fall through
          case 126: break;
          case 53:
            { return symbol(sym.GET);
            }
          // fall through
          case 127: break;
          case 54:
            { return symbol(sym.INT);
            }
          // fall through
          case 128: break;
          case 55:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 129: break;
          case 56:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 130: break;
          case 57:
            { return symbol(sym.COAL);
            }
          // fall through
          case 131: break;
          case 58:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 132: break;
          case 59:
            { return symbol(sym.ENDL);
            }
          // fall through
          case 133: break;
          case 60:
            { return symbol(sym.EXIT);
            }
          // fall through
          case 134: break;
          case 61:
            { return symbol(sym.GIFT);
            }
          // fall through
          case 135: break;
          case 62:
            { return symbol(sym.LOOP);
            }
          // fall through
          case 136: break;
          case 63:
            { return symbol(sym.SHOW);
            }
          // fall through
          case 137: break;
          case 64:
            { return symbol(sym.BOOLEAN_LITERAL, Boolean.parseBoolean(yytext()));
            }
          // fall through
          case 138: break;
          case 65:
            { return symbol(sym.VOID);
            }
          // fall through
          case 139: break;
          case 66:
            { return symbol(sym.WHEN);
            }
          // fall through
          case 140: break;
          case 67:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 141: break;
          case 68:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 142: break;
          case 69:
            { return symbol(sym.LOCAL);
            }
          // fall through
          case 143: break;
          case 70:
            { return symbol(sym.WORLD);
            }
          // fall through
          case 144: break;
          case 71:
            { return symbol(sym.DECIDE);
            }
          // fall through
          case 145: break;
          case 72:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 146: break;
          case 73:
            { return symbol(sym.STRING);
            }
          // fall through
          case 147: break;
          case 74:
            { return symbol(sym.NAVIDAD);
            }
          // fall through
          case 148: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
