
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Feb 01 21:38:45 CST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 50;
  public static final int SHOW = 42;
  public static final int POW = 11;
  public static final int STRING_LITERAL = 60;
  public static final int LBRACKET = 26;
  public static final int CHAR = 39;
  public static final int CHAR_LITERAL = 59;
  public static final int GE = 18;
  public static final int DECLBRACKETR = 29;
  public static final int LPAREN = 24;
  public static final int SEMI = 2;
  public static final int INT = 36;
  public static final int DECLBRACKETL = 28;
  public static final int FOR = 51;
  public static final int MINUS = 6;
  public static final int RPAREN = 25;
  public static final int BOOLEAN_LITERAL = 58;
  public static final int ENDL = 30;
  public static final int NOT = 23;
  public static final int AND = 21;
  public static final int LT = 15;
  public static final int DECIDE = 44;
  public static final int COAL = 32;
  public static final int OR = 22;
  public static final int BOOL = 38;
  public static final int COMMA = 3;
  public static final int GET = 43;
  public static final int NAVIDAD = 31;
  public static final int INC = 12;
  public static final int EXIT = 49;
  public static final int LOOP = 48;
  public static final int PLUS = 5;
  public static final int ASSIGN = 4;
  public static final int LE = 16;
  public static final int OF = 45;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int RBRACKET = 27;
  public static final int DIV_INT = 8;
  public static final int error = 1;
  public static final int MOD = 10;
  public static final int BREAK = 53;
  public static final int WORLD = 34;
  public static final int VOID = 41;
  public static final int EQ = 19;
  public static final int TIMES = 7;
  public static final int ARROW = 55;
  public static final int COLON = 14;
  public static final int ELSE = 46;
  public static final int DIV_FLOAT = 9;
  public static final int TO = 54;
  public static final int FLOAT = 37;
  public static final int NE = 20;
  public static final int END = 47;
  public static final int STRING = 40;
  public static final int LOCAL = 35;
  public static final int DEC = 13;
  public static final int FLOAT_LITERAL = 57;
  public static final int GT = 17;
  public static final int GIFT = 33;
  public static final int IDENTIFIER = 61;
  public static final int INTEGER_LITERAL = 56;
}

